kind: ConfigMap
apiVersion: v1
metadata:
  name: front-end-conf
  namespace: default
data:
  config.js: |
    window.env={'API_URL': '192.168.99.100:30649'}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: ses
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: ses
      tier: frontend
#      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: ses
        tier: frontend
#        track: stable
    spec:
      containers:
      - name: front-end
        image: anilpmm/smartenergy
        ports:
          - containerPort: 80
        volumeMounts:
        - name: config-vol
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
      volumes:
       - name: config-vol
         configMap:
           name: front-end-conf

#        lifecycle:
#          preStop:
#            exec:
#              command: ["/usr/sbin/nginx","-s","quit"]
