apiVersion: v1
kind: Service
metadata:
  labels:
    app: back-end
  name: back-end
spec:
  # clusterIP: None
  ports:
    - protocol: TCP
      port: 9000
  type: LoadBalancer
  selector:
    role: back-end
